#!/usr/bin/env python
import os
import pprint
import socket
import ssl
import sys

if len(sys.argv) != 3:
    print("Usage: print-cert-info hostname port", file=sys.stderr)
    sys.exit(os.EX_USAGE)

hostname, port = sys.argv[1:]
context = ssl.create_default_context()
context.check_hostname = False
conn = context.wrap_socket(socket.socket(socket.AF_INET),
                           server_hostname=hostname)
conn.connect((hostname, int(port)))
cert = conn.getpeercert()
pprint.pprint(cert)
conn.close()
